# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 301)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 40, 401, 172))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(10, 0, 10, 0)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.input_title = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_title.setObjectName("input_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_title)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.input_artist = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_artist.setObjectName("input_artist")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_artist)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.input_streams = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_streams.setObjectName("input_streams")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_streams)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.input_daily = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_daily.setObjectName("input_daily")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_daily)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.input_year = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_year.setObjectName("input_year")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.input_year)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.input_genre = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_genre.setObjectName("input_genre")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.input_genre)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nome da música:"))
        self.label_2.setText(_translate("Dialog", "Nome do artista:"))
        self.label_3.setText(_translate("Dialog", "Total de reproduções:"))
        self.label_4.setText(_translate("Dialog", "Recorde diário:"))
        self.label_5.setText(_translate("Dialog", "Ano de lançamento:"))
        self.label_6.setText(_translate("Dialog", "Gênero:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
